language: java
jdk:
  - openjdk8
  
script: "mvn cobertura:cobertura"
after_success:
  - bash <(curl -s https://codecov.io/bash)

branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - $HOME/.m2

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - ygygood@naver.com