language: java
jdk:
  - openjdk11
  
script: "mvn cobertura:cobertura"
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - codecov
env:
   - CODECOV_TOME=583d22f4-1c33-4b5f-91ad-a370a0290fab

branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - $HOME/.m2

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - ygygood@naver.com
   
# for sonaqube
addons:
  sonarcloud:
    organization: "giyeonyu"
    token:
      secure: "qyOYP8CouO1RgYTqzKYswRoPl0dMqCeLzivROE3zf9CFEkfHbQpquQgTsOL8XX3RU+SX9u5VryDf9Rm8hm5L3Oh8rsbEiVpekje+c5xRp5DwvxY83mEv1gdzHItWG9iW8KH27m9TrHoGT1aI/lnKL1H+xVuiDlCcAP8LIIGYx6mE4QI6CfopZYVVSegI1UmiQ20LKaIby54YXerst9VCDr34HD3mbifh4KwQrj8duRina8Iptbq2OLt5hdW/13tttt0I6AaHpzmhj2Fp4Da/ta2XF9sRUx0uLW+iw72dC6c0DUbsnZzNeiQBkE4F+z05DP0VGoXgbR+Qsvyzqu1fHwGSXkm8KRXwmUIPHtGI2hl97KGeevhfADKicZOIsUIajAcRC3wSaiXOwrRjZLIu/qw3n3oFKqUzv3kBECYFHvrgiE/eBdGD6mVbBIMtqgrmn5cWSP1j9Ftw1k3ZhrhsgWEMXbikwUJ2n9tOdW8UmfLpbXLvB3FxQv1UrxBIoIFpzrh7Hdtf+D+IDFNjgpj4GVFgF0dhiUqqm3tfUxO6/1NkKPXbw5rdcMIIztBjtw7WPTzYgitrX2kmCll47FzDBqePUbD6P5VRT++cNPqBAQploQ37+mC7fCiC/gBWMa0/JDVD3wRse9kEIN3Rwxdg45sC/bLSbxDzkVeuwsxrkeg=" # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  # - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.login=c1a58ac2e42e06851dd4e9c8de969a76a1d53a1f
