# This is a basic workflow to help you get started with Actions

name: telegram message
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: giyeonYu/checkout@master

      # Runs a single command using the runners shell
      - name: send custom message with args
        uses: giyeonYu/OSS@master
        with:
           to: ${{ secrets.TELEGRAM_TO }}
           token: ${{ secrets.TELEGRAM_TOKEN }}
           args: The ${{ github.event_name }} event triggered first step.

     
